import "./globals.css";

export const metadata = {
  title: "M-Tec.TH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#1B1B33]`}>{children}</body>
    </html>
  );
}
