/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",

  ],
  theme: {
    extend: {
      backgroundImage: {
        'Mainbg': 'linear-gradient(to right, #515299 15%, #CCAAE2 60%, #291D31 100%)',
        'Redbg': 'linear-gradient(to right, #DF2F55 0%, #791A2E 100%)',
        'Hero1bg': 'linear-gradient(315deg, #3D3E77 100%, #6162A8 100%)',
        'Hero1bg-1': 'linear-gradient(180deg, #515299 0%, #CCAAE2 50%, #291D31 100%)',
        'Aboutbg': 'linear-gradient(45deg, #282950 0%, #525493 100%)',
        'ch': "url('/hero1/ch.png')",
        'c1': "url('/hero1/c1.png')",
        'c2': "url('/hero1/c2.png')",
        'star': "url('/hero1/star.png')",
        'm1': "url('/hero1/m1.png')",
        'm2': "url('/hero1/m2.png')",
        'm3': "url('/hero1/m3.png')",
        'm4': "url('/hero1/m4.png')",
        'm5': "url('/hero1/m5.png')",
        'm6': "url('/hero1/m6.png')",
        'name': "url('/hero1/name.png')",
        'bg1': "url('/ls/bg1.png')",
        'bg2': "url('/ls/bg2.png')",
        'bg3': "url('/ls/bg3.png')",
        'blue': "url('/ls/blue.png')",
        'blue2': "url('/ls/blue2.png')",
        'blue3': "url('/ls/blue3.png')",
        'green1': "url('/ls/green1.png')",
        'green2': "url('/ls/green2.png')",
        'green3': "url('/ls/green3.png')",
        'cherry1': "url('/ls/cherry1.png')",
        'cherry2': "url('/ls/cherry2.png')",
        'cherry3': "url('/ls/cherry3.png')",
        'star2': "url('/Water1/star2.png')",
        'text': "url('/Water1/text.png')",
        'bg1-2': "url('/Water1/bg1.png')",
        'seed': "url('/Water1/seed.png')",
        'human': "url('/Water1/human.png')",
        'w1': "url('/Water1/w1.png')",
        'b2b': "url('/Water1/b2b.png')",
        'bg2-2': "url('/Water2/bg2.png')",
        'ww22': "url('/Water2/ww2.png')",
        'ww23': "url('/Water2/ww3.png')",
        'h1': "url('/Water2/h1.png')",
        'woman': "url('/Water2/woman.png')",
        'bg3-2': "url('/Water3/bg3.png')",
        'cw3': "url('/Water3/cw3.png')",
        'w31': "url('/Water3/w31.png')",
        'sleep': "url('/Water3/sleep.png')",
        'humanhead': "url('/Water3/humanhead.png')",
        'bgaa': "url('/About/bgaa.png')",
        'namecon': "url('/Contact/name.png')",
        'mail': "url('/Contact/mail.png')",
        'map': "url('/Contact/map.png')",
        'tel': "url('/Contact/tel.png')",
        'ig': "url('/Contact/ig.png')",
        'face': "url('/Contact/face.png')",
        'youtube': "url('/Contact/youtube.png')",
      },
      fontFamily: {
        'inter-bold': ['Inter-Bold', 'sans-serif'],
      },
      animation: {
        'move-up': 'moveup 0.7s ease-in-out',
        'up-down': 'updown 1.5s ease-in-out infinite alternate',
        'left-right': 'lr 1.5s ease-in-out infinite alternate',
        'left-right2': 'lr2 2s ease-in-out infinite alternate',
        'humann': 'human 1s ease-in-out infinite alternate'
      },
      keyframes: {
        moveup: {
          '0%': { transform: 'scale(0)' },
          '50%': { transform: 'scale(1.2)' },
          '100%': { transform: 'scale(1)' }, 
        },
        updown: {
          '0%': { transform: 'translateY(-8px)' },
          '100%': { transform: 'translateY(8px)' }, 
        },
        lr: {
          '0%': { transform: 'translateX(8px)' },
          '100%': { transform: 'translateX(-8px)' }, 
        },
        lr2: {
          '0%': { transform: 'rotate(10deg)' },
          '100%': { transform: 'rotate(-4deg)' }, 
        },
        human:{
          '0%': { backgroundImage:'url("/Water1/human.png")' },
          '100%': { backgroundImage:'url("/Water1/human2.png")' }, 
        },
      },
    },
  },
  plugins: [],
};
